# Generated by Django 4.1.3 on 2022-11-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='Dotor', max_length=25),
            preserve_default=False,
        ),
    ]
