# Generated by Django 4.1.3 on 2022-11-12 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_ticket_receipt_type_alter_disease_discovered_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='receipt_type',
        ),
        migrations.AlterField(
            model_name='disease',
            name='discovered_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 12, 12, 25, 59, 838401)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='receipt_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 12, 12, 25, 59, 837401)),
        ),
    ]
