# Generated by Django 4.1.3 on 2022-11-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_remove_customuser_email_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='FIO',
            new_name='fio',
        ),
    ]
