# Generated by Django 4.1.3 on 2022-11-13 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_remove_ticket_receipt_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='discovered_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 13, 18, 30, 17, 335002)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='receipt_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 13, 18, 30, 17, 333002)),
        ),
    ]
