# Generated by Django 4.1.3 on 2022-11-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0004_rename_fio_customuser_fio'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
